# wpilog-mcp installer for Windows
# Usage: irm https://raw.githubusercontent.com/TripleHelixProgramming/wpilog-mcp/main/install.ps1 | iex

$ErrorActionPreference = "Stop"
$repo = "TripleHelixProgramming/wpilog-mcp"
$installDir = Join-Path $env:USERPROFILE ".wpilog-mcp"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  wpilog-mcp Installer" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# --- Find Java ---

function Find-Java {
    # 1. WPILib JDK (scan for latest year)
    $wpilibDirs = @(
        (Join-Path $env:USERPROFILE "wpilib"),
        "C:\Users\Public\wpilib"
    )
    foreach ($base in $wpilibDirs) {
        if (Test-Path $base) {
            $years = Get-ChildItem -Path $base -Directory | Where-Object { $_.Name -match '^\d{4}$' } | Sort-Object Name -Descending
            foreach ($year in $years) {
                $javaExe = Join-Path $year.FullName "jdk\bin\java.exe"
                if (Test-Path $javaExe) {
                    Write-Host "Found WPILib $($year.Name) JDK: $javaExe" -ForegroundColor Green
                    return $javaExe
                }
            }
        }
    }

    # 2. JAVA_HOME
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\java.exe"))) {
        $javaExe = Join-Path $env:JAVA_HOME "bin\java.exe"
        Write-Host "Found JAVA_HOME: $javaExe" -ForegroundColor Green
        return $javaExe
    }

    # 3. System PATH
    $javaCmd = Get-Command java -ErrorAction SilentlyContinue
    if ($javaCmd) {
        Write-Host "Found java on PATH: $($javaCmd.Source)" -ForegroundColor Green
        return $javaCmd.Source
    }

    Write-Host "ERROR: Java 17+ is required but not found." -ForegroundColor Red
    Write-Host "Install the WPILib toolkit: https://docs.wpilib.org/en/stable/docs/zero-to-robot/step-2/wpilib-setup.html" -ForegroundColor Yellow
    exit 1
}

$javaExe = Find-Java

# Verify Java version >= 17
$versionOutput = & $javaExe -version 2>&1 | Select-Object -First 1
Write-Host "Java version: $versionOutput"
Write-Host ""

# --- Download latest release ---

Write-Host "Fetching latest release from GitHub..." -ForegroundColor Cyan
$releaseInfo = Invoke-RestMethod -Uri "https://api.github.com/repos/$repo/releases/latest" -Headers @{ "User-Agent" = "wpilog-mcp-installer" }
$version = $releaseInfo.tag_name -replace '^v', ''
$jarAsset = $releaseInfo.assets | Where-Object { $_.name -like "*-all.jar" } | Select-Object -First 1

if (-not $jarAsset) {
    Write-Host "ERROR: No JAR asset found in release $($releaseInfo.tag_name)" -ForegroundColor Red
    exit 1
}

Write-Host "Latest version: $version" -ForegroundColor Green
Write-Host ""

# --- Create directory structure ---

$jarsDir = Join-Path $installDir "jars"
$binDir = Join-Path $installDir "bin"
New-Item -ItemType Directory -Path $jarsDir -Force | Out-Null
New-Item -ItemType Directory -Path $binDir -Force | Out-Null

# --- Download JAR ---

$jarName = "wpilog-mcp-${version}.jar"
$jarPath = Join-Path $jarsDir $jarName

if (Test-Path $jarPath) {
    Write-Host "JAR already exists: $jarPath" -ForegroundColor Yellow
} else {
    Write-Host "Downloading $($jarAsset.name)..." -ForegroundColor Cyan
    Invoke-WebRequest -Uri $jarAsset.browser_download_url -OutFile $jarPath
    Write-Host "Downloaded: $jarPath" -ForegroundColor Green
}

# --- Create launcher script ---

$batContent = @"
@echo off
REM wpilog-mcp $version launcher
REM Auto-generated by install.ps1

REM Memory management is automatic. Set WPILOG_MAX_HEAP to control heap size.
set MAX_HEAP=%WPILOG_MAX_HEAP%
if "%MAX_HEAP%"=="" set MAX_HEAP=4g

REM Prefer WPILib JDK if available (scan for latest year)
set JAVA_EXEC=java
for /f "tokens=*" %%d in ('dir /b /ad /o-n "%USERPROFILE%\wpilib" 2^>nul') do (
    if exist "%USERPROFILE%\wpilib\%%d\jdk\bin\java.exe" (
        set JAVA_EXEC=%USERPROFILE%\wpilib\%%d\jdk\bin\java.exe
        goto :found
    )
)
for /f "tokens=*" %%d in ('dir /b /ad /o-n "C:\Users\Public\wpilib" 2^>nul') do (
    if exist "C:\Users\Public\wpilib\%%d\jdk\bin\java.exe" (
        set JAVA_EXEC=C:\Users\Public\wpilib\%%d\jdk\bin\java.exe
        goto :found
    )
)
:found

"%JAVA_EXEC%" -Xmx%MAX_HEAP% -jar "$($jarsDir.Replace('/', '\'))\$jarName" %*
"@

$batPath = Join-Path $binDir "wpilog-mcp.bat"
Set-Content -Path $batPath -Value $batContent -Encoding ASCII
Write-Host "Created launcher: $batPath" -ForegroundColor Green

# --- Create default config ---

$configPath = Join-Path $installDir "servers.yaml"
if (-not (Test-Path $configPath)) {
    $configContent = @"
# wpilog-mcp server configuration
# Documentation: https://github.com/TripleHelixProgramming/wpilog-mcp#configuration

# Your FRC team number (used for TBA match lookups)
team: 0

# Directory containing .wpilog files downloaded from the roboRIO
logdir: ~/riologs

# The Blue Alliance API key (get one at https://www.thebluealliance.com/account)
# tba_key: your-key-here

servers:
  # Default: stdio transport for MCP clients (Claude Desktop, etc.)
  default:
    transport: stdio

  # HTTP transport for browser-based or multi-client access
  http:
    transport: http
    port: 2363

  # Stress testing configuration
  stresstest:
    tba_key: ${TBA_API_KEY}
"@
    Set-Content -Path $configPath -Value $configContent -Encoding UTF8
    Write-Host "Created default config: $configPath" -ForegroundColor Green
    Write-Host "  Edit this file to set your team number and log directory." -ForegroundColor Yellow
} else {
    Write-Host "Config already exists: $configPath (not overwritten)" -ForegroundColor Yellow
}

# --- PATH instructions ---

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if already on PATH
$currentPath = [Environment]::GetEnvironmentVariable("Path", "User")
if ($currentPath -notlike "*$binDir*") {
    Write-Host "Add to your PATH (run this once):" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  [Environment]::SetEnvironmentVariable('Path', `$env:Path + ';$binDir', 'User')" -ForegroundColor White
    Write-Host ""
    Write-Host "Then restart your terminal." -ForegroundColor Yellow
} else {
    Write-Host "bin directory is already on your PATH." -ForegroundColor Green
}

Write-Host ""
Write-Host "Usage:" -ForegroundColor Cyan
Write-Host "  wpilog-mcp                    Start MCP server (stdio)" -ForegroundColor White
Write-Host "  wpilog-mcp start http         Start HTTP daemon" -ForegroundColor White
Write-Host ""
Write-Host "VS Code MCP setup - add to .vscode/mcp.json:" -ForegroundColor Cyan
Write-Host @"
  {
    "servers": {
      "wpilog": {
        "command": "$($batPath.Replace('\', '\\'))",
        "args": []
      }
    }
  }
"@ -ForegroundColor White
Write-Host ""
