apiVersion: v1
kind: Service
metadata:
  name: wpilog-dufs
  namespace: team401mcp
spec:
  selector:
    app: wpilog
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wpilog-mcp
  namespace: team401mcp
spec:
  selector:
    app: wpilog
  ports:
    - port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: wpilog-stats
  namespace: team401mcp
spec:
  selector:
    app: wpilog
  ports:
    - port: 80
      targetPort: 8001
